In [2]:
# import libraries
!pip install kaggle

Requirement already satisfied: kaggle in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (1.7.4.5)
Requirement already satisfied: bleach in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (from kaggle) (2025.6.15)
Requirement already satisfied: charset-normalizer in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (from kaggle) (3.4.2)
Requirement already satisfied: idna in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (from kaggle) (6.31.1)
Requirement already satisfied: python-dateutil>=2.5.3 in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (from kaggle) (72.1.0)
Requirement already satisfied: six>=1.10 in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /opt/anaconda3/envs/luke_barousse/lib/python3.13/site-packages (from kaggle) (0.5.1)

In [3]:
# download dataset using kaggle api
import kaggle
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /Users/shlok_manan_13/.kaggle/kaggle.json'
Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /Users/shlok_manan_13/.kaggle/kaggle.json'
Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv: Skipping, found more recently modified local copy (use --force to force download)

In [4]:
# read data from the file and handle null values
import pandas as pd
df = pd.read_csv('orders.csv', na_values=['Not Available', 'unknown'])

In [5]:
# rename column names, make them lower case and replace space with underscore
df.columns = [i.strip().lower().replace(' ', '_') for i in df.columns]

In [6]:
# check if the data is appropriate
df['ship_mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          9994 non-null   int64
 1   order_date        9994 non-null   object
 2   ship_mode         9988 non-null   object
 3   segment           9994 non-null   object
 4   country           9994 non-null   object
 5   city              9994 non-null   object
 6   state             9994 non-null   object
 7   postal_code       9994 non-null   int64
 8   region            9994 non-null   object
 9   category          9994 non-null   object
 10  sub_category      9994 non-null   object
 11  product_id        9994 non-null   object
 12  cost_price        9994 non-null   int64
 13  list_price        9994 non-null   int64
 14  quantity          9994 non-null   int64
 15  discount_percent  9994 non-null   int64
dtypes: int64(6), object(10)
memory usage: 1.2+ MB

In [8]:
# derive new columns discount, sale_price and profit
df['discount'] = df['list_price'] * df['discount_percent'] * 0.01
df['sale_price'] = df['list_price'] - df['discount']
df['profit'] = df['sale_price'] - df['cost_price']

In [9]:
# covert order date from object data type to datetime
df['order_date'] = pd.to_datetime(df['order_date'], format='%Y-%m-%d')

In [10]:
# drop cost_price, list_price and discount_percent columns
df.drop(columns=['cost_price','list_price','discount_percent'],inplace=True)

In [11]:
# removing the duplicates
df.drop_duplicates(inplace=True)

In [12]:
df.sample(10)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
1161,1162,2023-06-12,Second Class,Consumer,United States,Escondido,California,92025,West,Office Supplies,Art,OFF-AR-10004042,3,1.0,49.0,9.0
1135,1136,2023-11-22,Same Day,Consumer,United States,Homestead,Florida,33030,South,Office Supplies,Storage,OFF-ST-10001476,3,3.6,86.4,16.4
3048,3049,2022-05-04,First Class,Home Office,United States,Columbus,Georgia,31907,South,Furniture,Tables,FUR-TA-10004534,2,12.3,397.7,17.7
8405,8406,2023-02-10,Standard Class,Corporate,United States,Newark,Delaware,19711,East,Technology,Accessories,TEC-AC-10002473,5,4.2,135.8,15.8
2999,3000,2022-05-24,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19120,East,Technology,Machines,TEC-MA-10004521,3,8.4,201.6,1.6
388,389,2023-08-26,First Class,Consumer,United States,Cincinnati,Ohio,45231,East,Office Supplies,Art,OFF-AR-10004757,1,0.0,0.0,0.0
4780,4781,2023-02-25,Standard Class,Consumer,United States,Houston,Texas,77070,Central,Furniture,Chairs,FUR-CH-10002758,4,20.4,659.6,79.6
8350,8351,2023-06-26,Standard Class,Corporate,United States,Lawrence,Massachusetts,1841,East,Office Supplies,Paper,OFF-PA-10002689,1,0.5,9.5,-0.5
1289,1290,2022-05-08,Standard Class,Corporate,United States,New York City,New York,10009,East,Office Supplies,Art,OFF-AR-10001860,3,0.8,19.2,-0.8
3751,3752,2023-02-14,Second Class,Corporate,United States,Inglewood,California,90301,West,Furniture,Chairs,FUR-CH-10004886,3,9.2,220.8,30.8